version: '3.7'
services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - '185.119.57.47:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
    ports:
      - '185.119.57.47:5432'
  node-app:
    build: ./gate-simulator
    image: node-app:18.5.0
    ports:
      - '185.119.57.47:9999'